In [3]:
list_a = [0,1,1,2,3]
list_b = [5,8,13,21,34]

In [4]:
list_a + list_b

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [5]:
list_a * list_b

TypeError: can't multiply sequence by non-int of type 'list'

In [7]:
import numpy as np

A = np.array(list_a)
B = np.array(list_b)

In [9]:
A+B

array([ 5,  9, 14, 23, 37])

In [10]:
type(A)

numpy.ndarray

In [13]:
M1 = np.matrix([[1,0], [0,1]])
M2 = np.matrix([[0.5,2.0],[-4.0,2.5]])

In [14]:
M1+M2

matrix([[ 1.5,  2. ],
        [-4. ,  3.5]])

In [15]:
M1*M2

matrix([[ 0.5,  2. ],
        [-4. ,  2.5]])

In [16]:
M2.transpose()

matrix([[ 0.5, -4. ],
        [ 2. ,  2.5]])

In [17]:
A.shape

(5,)

In [18]:
M2.dtype

dtype('float64')

In [24]:
a = np.arange(12)
print(a[1:4]),
print(a[0:10:2])

[1 2 3]
[0 2 4 6 8]


In [25]:
np.array([np.arange(5),0.5*np.arange(5)])
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [26]:
marks = np.array([[8,7,9],[4.5,6,7.6],[8.5,10,9],[9,10,7.5]])

In [30]:
marks[:,0].max(),marks[:,0].min()

(9.0, 4.5)

In [31]:
marks[:,0].mean(),marks[:,0].std()

(7.5, 1.7677669529663689)

In [32]:
marks[:,0].sum()

30.0

In [33]:
from scipy import stats

In [34]:
from numpy import array,dot
from scipy import linalg


In [36]:
x = array([[1,10],[1,21],[1,29],[1,35]])
y = array([[0,9],[2,2],[3,1],[3,5]])

In [37]:
 n = linalg.inv(dot(x.T,x))
k = dot(x.T,x)
coef = dot(n,k)

In [38]:
print(coef)

[[ 1.00000000e+00  3.14193116e-14]
 [-1.38777878e-17  1.00000000e+00]]


In [39]:
from scipy import integrate
g = lambda x: np.exp(-x**2)
integrate.quad(g,0,np.inf)

(0.8862269254527579, 7.101318390472462e-09)

In [42]:
from scipy import optimize
f = lambda x: np.tan(x)-1
optimize.fsolve(f,0)

array([0.78539816])