In [1]:
list_a = [0, 1, 1, 2, 3]
list_b = [5, 8, 13, 21, 34] 

In [2]:
list_a + list_b

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [3]:
list_a * list_b

TypeError: can't multiply sequence by non-int of type 'list'

In [4]:
import numpy as np

A = np.array(list_a)
B = np.array(list_b) 

In [5]:
type(A)

numpy.ndarray

In [6]:
C = A + B
C


array([ 5,  9, 14, 23, 37])

In [7]:
M1 = np.matrix([[1, 0], [0, 1]])
M2 = np.matrix([[0.5, 2.0], [-4.0, 2.5]])

In [8]:
type(M1)

numpy.matrix

In [9]:
M1 + M2

matrix([[ 1.5,  2. ],
        [-4. ,  3.5]])

In [10]:
M1 * M2

matrix([[ 0.5,  2. ],
        [-4. ,  2.5]])

In [11]:
M2.transpose()

matrix([[ 0.5, -4. ],
        [ 2. ,  2.5]])

In [12]:
A.shape

(5,)

In [13]:
M2.shape

(2, 2)

In [14]:
A.dtype

dtype('int32')

In [15]:
M2.dtype

dtype('float64')

In [16]:
a = np.arange(12)
print(a[1:4]); print(a[0:10:2])


[1 2 3]
[0 2 4 6 8]


In [19]:
np.array([np.arange(5),0.5*np.arange(5)])

print(a)


[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [21]:
marks = np.array([[8, 9 ,7],
[4.5, 6, 3.5],
[8.5, 10, 9],
[8, 6.5, 9.5],
[9, 10, 7.5]])

marks[:, 0].max(), marks[:, 0].min()

(9.0, 4.5)

In [22]:
marks[:, 0].sum()

38.0

In [23]:
marks[:, 0].mean(), marks[:, 0].std()

(7.6, 1.5937377450509227)

In [24]:
import numpy as np
from scipy import stats 

In [25]:
from numpy import array, dot
from scipy import linalg

In [26]:
x = array([[1, 10], [1, 21], [1, 29], [1, 35]])
y = array([[0.9], [2.2], [3.1], [3.5]]) 

In [27]:
n = linalg.inv(dot(x.T, x))
k = dot(x.T, y)
coef = dot(n,k) 

In [28]:
print(coef)

[[-0.0955809 ]
 [ 0.10612972]]


In [29]:
a1 = np.array([[10, 30], [20, 40]])
linalg.det(a1)

-200.00000000000003

In [30]:
from scipy import integrate
g = lambda x: np.exp(-x**2)
integrate.quad(g, 0, np.inf)

(0.8862269254527579, 7.101318390915439e-09)

In [31]:
from scipy import optimize
f = lambda x: np.tan(x)-1
optimize.fsolve(f, 0)

array([0.78539816])