In [1]:
import pandas as pd

data = {
        "Name": ["Antonio", "Ziggy", "Bowman", "Kirk", "María"],
        "Physics": [8, 4.5, 8.5, 8, 9],
        "Spanish": [9, 6, 10, 6.5, 10],
        "History": [7, 3.5, 9, 9.5, 7.5]
    }

df = pd.DataFrame(data)

print(df)

      Name  Physics  Spanish  History
0  Antonio      8.0      9.0      7.0
1    Ziggy      4.5      6.0      3.5
2   Bowman      8.5     10.0      9.0
3     Kirk      8.0      6.5      9.5
4    María      9.0     10.0      7.5


In [4]:
import numpy as np
from scipy import stats
marks = np.array([[8, 9 ,7],
                  [4.5, 6, 3.5],
                  [8.5, 10, 9],
                  [8, 6.5, 9.5],
                  [9, 10, 7.5]])
stats.mode(marks)

ModeResult(mode=array([ 8. , 10. ,  3.5]), count=array([2., 2., 1.]))

In [7]:
import pandas as pd
cars = pd.read_csv('cars.csv')
cars.loc[:, 'mpg'].mode() 

0    10.4
1    15.2
2    19.2
3    21.0
4    21.4
5    22.8
6    30.4
Name: mpg, dtype: float64

In [8]:
ct = cars.groupby(['am'])
ct['mpg'].apply(lambda x: x.mode()) 

am   
0   0    10.4
    1    15.2
    2    19.2
1   0    21.0
    1    30.4
Name: mpg, dtype: float64

In [9]:
np.median(marks, axis=0) 

array([8. , 9. , 7.5])

In [10]:
cars.loc[:, 'mpg'].median() 

19.2

In [11]:
ct['mpg'].median()

am
0    17.3
1    22.8
Name: mpg, dtype: float64

In [13]:
max_physics = df["Physics"].max()
print("Maximum value in Physics:", max_physics)

Maximum value in Physics: 9.0


In [16]:
min_physics = df['Physics'].min()
print("Minimum value in physics:", min_physics)

Minimum value in physics: 4.5


In [21]:
physics_range = max_physics - min_physics
print(physics_range)

4.5


In [26]:
ptp_physics = np.ptp(df['Physics'])
print(ptp_physics)

4.5


In [28]:
print('Physics Q1: ', np.quantile(df['Physics'], 0.25))
print('Physics Q2: ', np.quantile(df['Physics'], 0.50))
print('Physics Q3: ', np.quantile(df['Physics'], 0.75))

Physics Q1:  8.0
Physics Q2:  8.0
Physics Q3:  8.5


In [29]:
np.quantile(marks, [0.25, 0.5, 0.75], axis=0)

array([[ 8. ,  6.5,  7. ],
       [ 8. ,  9. ,  7.5],
       [ 8.5, 10. ,  9. ]])

In [30]:
mpg = cars.loc[:, 'mpg']
print('MPG Q1: ', mpg.quantile(0.25))
print('MPG Q2: ', mpg.quantile(0.50))
print('MPG Q3: ', mpg.quantile(0.75))

MPG Q1:  15.425
MPG Q2:  19.2
MPG Q3:  22.8


In [31]:
print(mpg.quantile([0.1, 1]))

0.1    14.34
1.0    33.90
Name: mpg, dtype: float64


In [32]:
def md(x, axis=None):
    avg = np.mean(x, axis)
    dev = np.absolute(x - avg)
    return np.mean(dev, axis)

In [35]:
physics = df['Physics']

md(physics)

1.2400000000000002

In [36]:
md(marks, axis=0)

array([1.24, 1.64, 1.64])

In [37]:
np.var(physics)

2.54

In [38]:
np.std(physics)

1.5937377450509227

In [39]:
np.var(physics, ddof=1)

3.175

In [40]:
np.std(physics, ddof=1)

1.7818529681205462

In [41]:
np.var(marks, axis=0, ddof=1)

array([3.175, 3.7  , 5.575])

In [42]:
np.std(marks, axis=0, ddof=1)

array([1.78185297, 1.92353841, 2.36114379])

In [43]:
mpg.var(ddof=0)

35.188974609375

In [44]:
mpg.std(ddof=0)

5.932029552301219